### PR TITLE
Sync changes to address book address to applicable carts

### PR DESCRIPTION
**Pull request by nfourtythree**
### Description
~By setting the `syncAddressBookChanges` config setting to `true`, when a user saves an address in their address book that is being used as a source address for a cart (`sourceBillingAddressId`, `sourceShippingAddressId`) the respective addresses will be updated on the cart.~

~This new setting is `false` by default to preserve the current behaviour in Commerce 4 and not cause any issues for developers/project owners when updating.~

When updating an address in a user's address book, if that user's address is used as a source address on any carts. These carts should be updated with the new address details.

### Related issues
#3178

### CODE REVIEW

**Comment by bossanova808** [comment]
I may well be misreading this, but this feels a little bit the wrong way around to me.  The idea is, if a user changes an address they are using for a cart, that change is then automatically propagated back to the address book.   That is because, naturally, people will load and use (and edit) addresses, during checkout, as the most common flow (& I am currently implementing this with a call to save-address).

 Here it seems like you're implementing something else - if they change an address in their address book, whilst it is set on the cart, it should change there too.  I suppose that is true, too - albeit it will be a relatively unusual flow.

**Comment by nfourtythree** [comment]
Hi @bossanova808 

Thank you for your feedback. We are trying to cover the many use cases people have for Commerce. Address books, custom addresses directly on the cart etc.

With this fix, we have hit a spot where those things are all now possible. With users and their address books, this idea is based on how places like Amazon and Shopify deal with their addresses. You are selecting an address from your address book to use on the cart and if you want to update that address, it should happen within the address book system.

If you were to pull down a fresh install of Commerce 4 and take a look at the updated example templates from this PR I think things would start to make more sense. We need to get this information and explanation into the documentation (and examples in there) to do a better job of educating developers on what is possible.

We have definitely taken your point on board and it has caused us to have discussions and make notes internally on what else may or may not be required regarding addresses during checkout in the future.

Thanks!

**Comment by bossanova808** [comment]
Thanks for the extra info.  

Stupid question perhaps, but what is actually the best/recommended  way to get a vanilla Commerce install going these days - the Craft starter project doesn't include Commerce, right?  Should one use that and then manually add Commerce, or is there a more direct way?    (Be nice is there was a Commerce included version, but I don't think that exists?)

**Comment by nfourtythree** [comment]
@bossanova808 the steps you have outlined with the Craft starter will probably be the quickest way currently. A suggestion of a Commerce start is a good idea, will take this back to the team to see if we can add it to the road map.

Thanks!

**Pull request merged**
