### PR TITLE
Add order context to isPurchasableShippable in class ShippingMethod

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by lukeholder** [comment]
I also added the optional param to other places that have the context and call the method. Will be in the next release. Thanks.

**Comment by nfourtythree** [comment]
Commerce `4.3.1` has now been released with these changes.

**Comment by boboldehampsink** [comment]
Thanks @nfourtythree, please let me know when it is in 3.x too, thanks!

**Comment by nfourtythree** [comment]
This is in `3.4.23` which has just been released!

**Pull request merged**
