### PR TITLE
Bugfix/payment currency convert

### PR DESCRIPTION
**Pull request by lukeholder**
### Description

Compatible fix for https://github.com/craftcms/commerce/pull/2223

### CODE REVIEW

**Comment by lukeholder** [comment]
@joostwaaijer @boboldehampsink I believe this PR fixes the issue also. Does this work in your instance?

**Comment by joostwaaijer** [comment]
@lukeholder Tested it, and it's working! Thanks!

**Comment by joostwaaijer** [comment]
@lukeholder Could you also take a look at this PR: https://github.com/craftcms/commerce-omnipay/pull/23, it's related to the same issue

**Review by boboldehampsink — APPROVED** [review]

**Comment by boboldehampsink** [comment]
@lukeholder ready to merge 👍

**Comment by lukeholder** [comment]
@boboldehampsink yes, merging today

**Pull request merged**
