### PR TITLE
Check the order->dateOrdered is object when completing order

### PR DESCRIPTION
**Pull request by samuelbirch**
It was throwing an error when the order->dateOrdered was being returned as a DateTime object and then trying to use it to create a new DateTime object. So this is a little check before trying to create a new object.

### CODE REVIEW

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

Thanks for the PR. In what scenario was the error manifesting?

Thanks.

**Comment by samuelbirch** [comment]
Hi @nfourtythree 

If an order has been created but not completed and no transactions (guess you could use an active cart, we created the order with admin-orders), then if you click the "complete order" button, at that point the error was being thrown.

**Comment by nfourtythree** [comment]
Ah ok, so this is because an order shouldn't have a `dateOrdered` value before it is completed if that makes sense. Completing the order is what gives the order its `dateOrdered` value.

So in the normal operations of Commerce this error wouldn't exist.

**Comment by samuelbirch** [comment]
If i add something to my cart as normal via the frontend, the login to the backend and go to active carts. If i view the details of that active cart and click the "complete order" button I get the error. Admin orders plugin not involved in this case.

**Comment by nfourtythree** [comment]
Hmm, I thought I had just tested this and it was working fine. Let me go back and double-check.

Thanks for the info!

**Comment by nfourtythree** [comment]
Hey @samuelbirch 

Have just tested it again and I did the same. Create a cart in the front end all the way up to payment and then completed it in the CP and it worked correctly.

Here is a video: http://x.n43.me/20a61713d4c1

It seems like there might be something else at play here?

**Comment by samuelbirch** [comment]
yeah it seems like there could be something else at play. 

Ok, leave it with me. I'd do some more testing to try and pin point the source.

Thanks for taking the time with this :)

**Comment by lukeholder** [comment]
Please let us know if you figure it out. Thanks.

**Pull request closed without merging**
