### PR TITLE
Fix case-sensitive coupon codes

### PR DESCRIPTION
**Pull request by boboldehampsink**
### Description
Fixes case-sensitive coupon codes check by moving it to the database instead of via php.

### Related issues

#2249

### CODE REVIEW

**Comment by boboldehampsink** [comment]
@lukeholder updated this to be based off of 3.4

**Comment by boboldehampsink** [comment]
Please don't ignore this issue, I have this fork running in production because it's broken. cc @brandonkelly

**Comment by angrybrad** [comment]
`ilike` is Postgres specific, so this would break MySQL. Seems like the correct fix for this is to normalize the coupon codes to lowercase on the initial save and have all of the subsequent checks do the same when comparing? @lukeholder @nfourtythree

**Comment by boboldehampsink** [comment]
Oops, I thought it was for MySQL too. We can do a lowercase == lowercase check on the same lines tho.

**Comment by boboldehampsink** [comment]
@angrybrad made the ilike conditional for postgres only and rebased on develop

**Comment by angrybrad** [comment]
@boboldehampsink thanks for that. I still think normalization is the safer bet because MySQL case sensitivity can vary per collation, but will talk it over with the Commerce team.

**Comment by lukeholder** [comment]
Going to go with your solution @boboldehampsink which is inline with

https://github.com/craftcms/cms/blob/develop/src/services/Users.php#L175-L200

Cutting a release shortly

**Comment by boboldehampsink** [comment]
Thanks guys

**Comment by lukeholder** [comment]
3.4.1 is now out with this PR included.

**Pull request merged**
