### PR TITLE
Initial work on making it clearer how category relationships work with promotions.

### PR DESCRIPTION
**Pull request by lukeholder**
Welcome @mattstein to make it more clear in the field instructions - will then extend this to sales.

### CODE REVIEW

**Comment by lukeholder** [comment]
Fixed #1560

**Comment by lukeholder** [comment]
Also fixed the migration for people upgrading to Commerce 3. They should stay on sourceElement relation type.

**Comment by lukeholder** [comment]
@mattstein merged it for this release, but welcome your input still on the option labels.

**Comment by mattstein** [comment]
Sorry I didn’t respond sooner, @lukeholder!

I did a quick mockup thinking through this, and while it’s probably annoying scope creep I think it’d be most useful to illustrate how the relationship match works:

category-promotion-mockup

This is a challenging thing to conceptualize, so using a radio field puts the options side by side for the user to compare and consider. Simply illustrating the options could potentially make it easier to understand, save some language, and potentially avoid a trip to the (more technical) docs.

I tried to also focus the language from the perspective of the categories, since we’re choosing them here, which could be problematic since I think the wording of the current options is focused on the purchasables. (Note how the illustrations are the inverse of what they describe.)

Happy to chat further or refine, or just run and hide if this is TMI! :)

**Comment by mattstein** [comment]
Also I’m aware that’s pretty hideous so please consider it an illustration and not design work.

**Pull request merged**
