### PR TITLE
Fixed type

### PR DESCRIPTION
**Pull request by importantcoding**

### CODE REVIEW

**Comment by dhahn** [comment]
I hope the typo in this pull request title is on purpose.

**Comment by importantcoding** [comment]
I DO WHAT I WANT!

**Comment by importantcoding** [comment]
Should I sit on everything and request a pull for all at once or do it like this? I'm unsure how it's preferred.

**Comment by dhahn** [comment]
I dunno what pixel and tonic prefer, but I'd suggest combining related pieces like typos you find into one pull request. A bit less work for the maintainers.

**Comment by lukeholder** [comment]
Thanks.

**Pull request merged**
