### PR TITLE
Reset Data Console Command

### PR DESCRIPTION
**Pull request by nfourtythree**
### Description
This adds a console command for resetting Commerce data. The command takes the following actions:

- Deletes all orders/carts
- Deletes all subscriptions
- Deletes all payment sources
- Deletes all guest customers
- Deletes all addresses (for both guest and user customers)
- Resets all discount usage counters (total uses, customer usage and email usage)

This is useful for people developing to be able to clear any data before migrating the database.

A prompt is given before the reset action takes place.

### Related issues
#581

### CODE REVIEW

**Comment by lukeholder** [comment]
Awesome thanks

**Comment by KatieMFritz** [comment]
I notice there are still rows in my `craft_commerce_customers_addresses` table after I run the command. Where are those coming from?

**Comment by nfourtythree** [comment]
Hi @KatieMFritz 

The `commerce_customers_addresses` table has cascade deletes for when an address or a customer is deleted. So these records should be removed when the parent data is removed.

Do the customer IDs in the table actually still have records in the `commerce_customers` table?

**Comment by KatieMFritz** [comment]
Sorry for the delayed response!

Yes, the `commerce/reset-data` command leaves customers. It does delete orders.

**Comment by KatieMFritz** [comment]
Oh, is it maybe because they're not guest customers?

**Comment by nfourtythree** [comment]
Hi @KatieMFritz 

All users have a customer record. These customer records do not get deleted when using the `reset-data` command.

Thanks!

**Pull request merged**
