### PR TITLE
Fix order status emails project config

### PR DESCRIPTION
**Pull request by boboldehampsink**
Make sure emails are processed first

### CODE REVIEW

**Comment by andris-sevcenko** [comment]
❤️

**Comment by boboldehampsink** [comment]
Thanks Andris. Sorry, forgot changelog entry again.

**Comment by andris-sevcenko** [comment]
I'll add it in a bit!

**Comment by boboldehampsink** [comment]
Thanks :-)

**Comment by andris-sevcenko** [comment]
Finally! b7fd8a58b0dfe852d091b1489cce7d84c5dc571d

**Pull request merged**
