### PR TITLE
Extend graphql product default variant fields and arguments

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by lukeholder** [comment]
Thanks!

**Comment by lukeholder** [comment]
This will be in the next release.

**Comment by lukeholder** [comment]
This is now fixed in 4.3.2

**Comment by boboldehampsink** [comment]
@lukeholder it isn't published yet, is it? composer update doesn't find it

**Comment by lukeholder** [comment]
@boboldehampsink sorry the tag was not pushed. It's now up.

**Pull request merged**
